version: '3.8'
services:
  skywalking-oap:
    image: apache/skywalking-oap-server:latest
    container_name: skywalking-oap
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    healthcheck:
      test: ["CMD-SHELL", "/skywalking/bin/swctl"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      JAVA_OPTS: "-Xms512m -Xmx512m"
  skywalking-ui:
    image: apache/skywalking-ui:latest
    container_name: skywalking-ui
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap
    restart: always
    ports:
      - 3380:8080
    environment:
      SW_OAP_ADDRESS: skywalking-oap:12800