# confluence 文档管理系统
version: '3'

services:
  jira-mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    container_name: jira-mysql
    volumes:
     - jira-data:/var/lib/mysql
    ports:
     - "33306:3306"
    environment:
     MYSQL_ROOT_PASSWORD: password123

  jira-server:
    image: cptactionhank/atlassian-jira-software:7.13.1
    restart: unless-stopped
    container_name: jira-server
    privileged: true
    ports:
      - "38080:8080"
    depends_on:
     - jira-mysql

volumes:
  jira-data: