# docker 容器管理监控平台
version: '3'
services:
    portainer:
      image: 'portainer/portainer'
      restart: always
      container_name: some-portainer
      ports:
        - '9900:9000'
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - data:/data
volumes:
    data: