version: '3'

services:
  ikev2:
    image: gaomd/ikev2-vpn-server:0.3.0
    restart: always
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    container_name: ikev2-vpn-server