# nginx 服务器
version: '3.1'

services:
  nginx:
    image: nginx:1.15
    restart: unless-stopped
    container_name: some-nginx
    ports:
      - 8080:80
      - 443:443
    volumes:
      - /tmp/own/nginx/confs:/etc/nginx/conf.d
      - /tmp/own/nginx/log:/var/log/nginx
      - /tmp/own/nginx/www:/var/www

