version: '3'

services:
  mongodb:
    image: mongo:4.1
    restart: unless-stopped
    container_name: mock-mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - easy-mock

  redis:
    image: redis:4.0.6
    command: redis-server --appendonly yes
    container_name: mock-redis
    volumes:
      # ./data/redis redis 数据文件存放地址，根据需要修改为本地地址
      - './data/redis:/data'
    networks:
      - easy-mock

  web:
    image: easymock/easymock:1.6.0
    container_name: mock-web
    command: /bin/bash -c "npm start"
    ports:
      - 7300:7300
    volumes:
      # ./logs 日志地址，根据需要修改为本地地址
      - './logs:/home/easy-mock/easy-mock/logs'
      # ./production.json 配置地址，请使用本地配置地址替换
      - './production.json:/home/easy-mock/easy-mock/config/production.json'
    networks:
      - easy-mock

networks:
  easy-mock:
volumes:
  data: