# 暂时未进行启动尝试
version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:6.7.0
    container_name: elk-elasticsearch
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  kibana:
    image: kibana:6.7.0
    container_name: elk-kibana
    environment:
      #SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    #volumes:
    #  - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
  logstash:
      image: logstash:7.0.1
      container_name: elk-logstash
      #volumes:
      #  - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      #  - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      ports:
        - 5044:5044
        - 9600:9600
      environment:
        LS_JAVA_OPTS: "-Xmx256m -Xms256m"