# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:6.7.0
    container_name: skywalking-es
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      #discovery.type: single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  oap:
    image: apache/skywalking-oap-server:6.0.0-GA
    container_name: skywalking-oap
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: unless-stopped
    ports:
      - 11800:11800
      - 12800:12800
    volumes:
      - ./config:/skywalking/config:ro
  ui:
    image: apache/skywalking-ui:6.0.0-GA
    container_name: skywalking-ui
    depends_on:
      - oap
    links:
      - oap
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      collector.ribbon.listOfServers: localhost:12800
      collector.ribbon.ReadTimeout: 20000