# mysql 数据库
version: '3.1'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    container_name: some-mysql
    privileged: true
    volumes:
     - mysql-data:/var/lib/mysql
     - './conf:/etc/mysql/conf.d'
    ports:
     - "3306:3306"
    environment:
     MYSQL_ROOT_PASSWORD: password123


volumes:
  mysql-data: