# confluence 文档管理系统
version: '3'

services:
  confluence-mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    container_name: confluence-mysql
    volumes:
     - confluence-data:/var/lib/mysql
     - './conf:/etc/mysql/conf.d'
    ports:
     - "13306:3306"
    environment:
     MYSQL_ROOT_PASSWORD: password123

  confluence-server:
    image: atlassian/confluence-server:6.15.6
    restart: unless-stopped
    container_name: confluence-server
    ports:
      - "18090:8090"
    depends_on:
     - confluence-mysql

volumes:
  confluence-data: