# vsftpd搭建
version: '3.3'
services:
  vsftpd:
    image: fauria/vsftpd
    container_name: some-vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - "/home/ftp/data:/home/vsftpd"
    environment:
      - FTP_USER=myuser
      - FTP_PASS=mypass
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    restart: unless-stopped