# mongo 文档数据库
version: '3.1'

services:

  mongo:
    image: mongo:4.1
    restart: unless-stopped
    container_name: some-mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      #- /my/own/datadir:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin123456
#
#  mongo-express:
#    image: mongo-express
#    restart: unless-stopped
#    container_name: some-mongo-express
#    ports:
#      - 18001:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123456
#      # web管理台账户密码
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: admin123456
volumes:
  data: